# Generated by Django 3.0.7 on 2023-03-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230226_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
